version: '2'
services:
  authelia-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./scripts:/usr/app/scripts
      - ./server:/usr/app/server
      - ./shared:/usr/app/shared
      - ./config.template.yml:/usr/app/config.yml:ro
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on: 
      - redis
    networks:
      example-network:
        aliases:
          - authelia
